<?php

/**
 * @file
 * Contains service_club_passwords.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function service_club_passwords_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the service_club_passwords module.
    case 'help.page.service_club_passwords':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Removes passwords from user creation.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 * Using sha512 to generate a password.
 */
function service_club_passwords_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_register_form') {
    $mail_description = t('A valid email address. All emails from the system will be sent to this address. The email address is not made public and will only be used to send you a login link or if you wish to receive certain news or notifications by email.');
    if (!empty($form['account']['mail'])) {
      $form['account']['mail']['#description'] = $mail_description;
    }
    // Hides the password field, and populates it with a random password.
    $form['account']['pass']['#type'] = 'value';
    $hashVal = hash('sha512', user_password());
    $form['account']['pass']['#value'] = $hashVal;
  }
}

